# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Test and Build
        caches:
          - node
        script:
          - npm install
          - npm test -- --reporters=default --reporters=jest-junit
          - npm run build
        artifacts:
          - build/**
          - node_modules
    - step:
        name: Deploy
        script:
          - wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | apt-key add -
          - apt-get update
          - apt-get install cf-cli
          - cf --version
          - cf login -a https://api.run.pivotal.io -u $PIVOTAL_USERNAME -p $PIVOTAL_PASSWORD
          - cf push react-workers
    - step:
        name: E2E Tests
        image: selenium/standalone-chrome:3.141.59-oxygen
        script:
          - sudo apt-get update
          - sudo apt-get install nodejs
          - npm install
          - npm run e2e:results
