# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        name: Test and Build
        caches:
          - node
        script:
          - npm install
          - npm test -- --reporters=default --reporters=jest-junit
          - npm run build
        artifacts:
          - build/**
    - step:
        name: Deploy
        script:
          - apt-get update
          - wget -O /tmp/cf-cli.tgz "https://cli.run.pivotal.io/stable?release=linux64-binary&version=6.45.0"
          - ls -alF /tmp/
          - mkdir -p /usr/local/bin
          - tar -xzf /tmp/cf-cli.tgz -C /usr/local/bin
          - cf --version
          - cf login -a https://api.run.pivotal.io -u $PIVOTAL_USERNAME -p $PIVOTAL_PASSWORD
          - cf push react-workers
    - step:
        name: E2E Tests
        caches:
          - node
        image: selenium/standalone-chrome:3.141.59-oxygen
        script:
          - npm install
          - npm run e2e:results
